### ISSUE TITLE
NPE on hover

### ISSUE THREAD

**Issue by sestegra** [lingua-pupuli/puppet-vscode#507]
### What Versions are you running?
OS Version: Windows 10 Build 16299
VSCode Version: 1.33.1
Puppet Extension Version: 0.18
Puppet Agent Version: N/A
PDK Version (if applicable): 1.10

### What You Are Seeing?
On following code, when hovering on `${path_base_dir}`, a NPE occurs

``` ruby
class foo
{
  $path_base_dir = '/etc/bar'
  $path_cfg      = "${path_base_dir}/foo.conf"
}
```

```
[2019-05-15 15:51:56.158] [renderer1] [error] Cannot read property 'kind' of null: TypeError: Cannot read property 'kind' of null
	at asHoverContent (C:\Users\user\.vscode\extensions\jpogran.puppet-vscode-0.18.0\node_modules\vscode-languageclient\lib\protocolConverter.js:101:27)
	at asHover (C:\Users\user\.vscode\extensions\jpogran.puppet-vscode-0.18.0\node_modules\vscode-languageclient\lib\protocolConverter.js:134:31)
```

### What is Expected?
No exception

### How Did You Get This To Happen? (Steps to Reproduce)
- Hover on `${path_base_dir}`
- Open **Output** of **Log(Windows)**

### Output Log
```
DEBUG: 2019-05-15T13:45:03.815Z Registered extension.pdkNewModule command
DEBUG: 2019-05-15T13:45:03.815Z Registered extension.pdkNewClass command
DEBUG: 2019-05-15T13:45:03.815Z Registered extension.pdkNewTask command
DEBUG: 2019-05-15T13:45:03.815Z Registered extension.pdkValidate command
DEBUG: 2019-05-15T13:45:03.815Z Registered extension.pdkTestUnit command
DEBUG: 2019-05-15T13:45:03.815Z Found a valid Puppet installation at C:\Program Files\Puppet Labs\DevelopmentKit\puppet
DEBUG: 2019-05-15T13:45:03.815Z Setting status bar to Initializing
DEBUG: 2019-05-15T13:45:03.816Z Configuring language client options
DEBUG: 2019-05-15T13:45:03.816Z Creating server options
DEBUG: 2019-05-15T13:45:03.816Z [getRubyEnvFromPDK] Using environment variable DEVKIT_BASEDIR=C:\Program Files\Puppet Labs\DevelopmentKit
DEBUG: 2019-05-15T13:45:03.816Z [getRubyEnvFromPDK] Using environment variable GEM_HOME=C:\Program Files\Puppet Labs\DevelopmentKit\share\cache\ruby\2.1.0
DEBUG: 2019-05-15T13:45:03.816Z [getRubyEnvFromPDK] Using environment variable GEM_PATH=C:\Program Files\Puppet Labs\DevelopmentKit\private\ruby\2.1.9\lib\ruby\gems\2.1.0;C:\Program Files\Puppet Labs\DevelopmentKit\share\cache\ruby\2.1.0;C:\Program Files\Puppet Labs\DevelopmentKit\private\puppet\ruby\2.1.0
DEBUG: 2019-05-15T13:45:03.816Z [getRubyEnvFromPDK] Using environment variable RUBY_DIR=C:\Program Files\Puppet Labs\DevelopmentKit\private\ruby\2.1.9
DEBUG: 2019-05-15T13:45:03.816Z [getRubyEnvFromPDK] Using environment variable RUBYLIB=C:/Program Files/Puppet Labs/DevelopmentKit/lib;
DEBUG: 2019-05-15T13:45:03.816Z [getRubyEnvFromPDK] Using environment variable PATH=C:\Program Files\Puppet Labs\DevelopmentKit\bin;C:\Program Files\Puppet Labs\DevelopmentKit\private\ruby\2.1.9\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseSVN\bin;D:\programs\Git\cmd;C:\Program Files\TortoiseGit\bin;C:\Program Files\Puppet Labs\Puppet\bin;C:\Users\user\scoop\apps\python\current\Scripts;C:\Users\user\scoop\apps\nodejs\current\bin;C:\Users\user\scoop\apps\nodejs\current;C:\Users\user\go\bin;C:\Users\user\scoop\shims;C:\Users\user\AppData\Local\Microsoft\WindowsApps;C:\Users\user\AppData\Local\Programs\Microsoft VS Code\bin
DEBUG: 2019-05-15T13:45:03.816Z [getRubyEnvFromPDK] Using environment variable RUBYOPT=rubygems
DEBUG: 2019-05-15T13:45:03.816Z [getRubyEnvFromPDK] Editor Services will invoke with: C:\Program Files\Puppet Labs\DevelopmentKit\private\ruby\2.1.9\bin\ruby c:\Users\user\.vscode\extensions\jpogran.puppet-vscode-0.18.0\vendor\languageserver\puppet-languageserver --stdio --timeout=10 --puppet-version=4.8.2
DEBUG: 2019-05-15T13:45:03.816Z Creating language client
DEBUG: 2019-05-15T13:45:03.818Z Setting status bar to Initialization Complete
DEBUG: 2019-05-15T13:45:03.818Z Configuring Local::stdio connection handler
DEBUG: 2019-05-15T13:45:03.818Z Setting status bar to Starting languageserver
DEBUG: 2019-05-15T13:45:03.818Z Registered Format Document provider
DEBUG: 2019-05-15T13:45:03.818Z Registered extension.puppetShowNodeGraphToSide command
DEBUG: 2019-05-15T13:45:03.818Z Registered onDidSaveTextDocument for node graph event handler
DEBUG: 2019-05-15T13:45:03.818Z Registered DebugAdapterDescriptorFactory for Puppet
DEBUG: 2019-05-15T13:45:03.818Z Registered DebugConfigurationProvider for Puppet
DEBUG: 2019-05-15T13:45:04.656Z pdk shell started, pid: 16736
DEBUG: 2019-05-15T13:45:06.343Z Setting status bar to Loading Puppet
DEBUG: 2019-05-15T13:45:08.817Z Setting status bar to 4.8.2
DEBUG: 2019-05-15T13:45:08.840Z Setting status bar to 4.8.2
DEBUG: 2019-05-15T13:45:09.362Z Setting status bar to 4.8.2
DEBUG: 2019-05-15T13:45:10.346Z Setting status bar to 4.8.2
DEBUG: 2019-05-15T13:45:11.357Z Setting status bar to 4.8.2
```

**Comment by jpogran** [comment]
You're running into an exception because the Symbol provider doesn't support Puppet 4.X. Puppet v4.X does not give us the same AST info that Puppet 5.X and above does, so we just can't give the same information in hover.

We should however not throw exceptions here, we should either be emitting a warning about version compatibility or silently failing.

**Comment by jpogran** [comment]
note to transfer to puppet-editor-services
