### ISSUE TITLE
An error occured while the Language Server was starting. The server has been disabled. Source: Puppet (Extension)

### ISSUE THREAD

**Issue by skywaymsn** [lingua-pupuli/puppet-vscode#574]
### What Versions are you running?

OS Version: Windows 10 Enterprise
VSCode Version: 1.39.1
Puppet Extension Version: 0.21.0
PDK Version: 1.14.0.0
`Ruby version: 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]`

### What You Are Seeing?
An error occured while the Language Server was starting. The server has been disabled. Source: Puppet (Extension)

**Note: Running Ruby 2.6.5**
I did not try Ruby 2.5.

It is acting like it can't find some gems (see log debug below), but it doesn't call out any specific gem or version.

I did try to install the puppet gem (gem install puppet) and it complained about gem compatibility, aka:

```
gem install puppet
ERROR:  Error installing puppet:
        The last version of ffi (~> 1.9.25) to support your Ruby & RubyGems was 1.9.25. Try installing it with `gem install ffi -v 1.9.25` and then running the current command again
        ffi requires Ruby version >= 2.0, < 2.6. The current ruby version is 2.6.5.114.

```

Which I resolved with:
```
 gem install ffi --version '=1.9.25' --force
Successfully installed ffi-1.9.25-x64-mingw32
Parsing documentation for ffi-1.9.25-x64-mingw32
Installing ri documentation for ffi-1.9.25-x64-mingw32
Done installing documentation for ffi after 1 seconds
1 gem installed
```

After this, Puppet gem installed OK:
```
gem install puppet
Successfully installed facter-2.5.6-x64-mingw32
Successfully installed hiera-3.5.0
Successfully installed semantic_puppet-1.0.2
Successfully installed fast_gettext-1.8.0
Successfully installed locale-2.1.2
Successfully installed multi_json-1.14.1
Successfully installed httpclient-2.8.3
Successfully installed hocon-1.2.5
Successfully installed puppet-resource_api-1.8.7
Successfully installed concurrent-ruby-1.1.5
Successfully installed win32-dir-0.4.9
Successfully installed win32-process-0.7.5
Successfully installed win32-security-0.2.5
Successfully installed win32-service-0.8.8
The `minitar` executable is no longer bundled with `minitar`. If you are
expecting this executable, make sure you also install `minitar-cli`.
Successfully installed minitar-0.6.1
Successfully installed puppet-6.10.0-x64-mingw32
Parsing documentation for facter-2.5.6-x64-mingw32
Installing ri documentation for facter-2.5.6-x64-mingw32
Parsing documentation for hiera-3.5.0
Installing ri documentation for hiera-3.5.0
Parsing documentation for semantic_puppet-1.0.2
Installing ri documentation for semantic_puppet-1.0.2
Parsing documentation for fast_gettext-1.8.0
Installing ri documentation for fast_gettext-1.8.0
Parsing documentation for locale-2.1.2
Installing ri documentation for locale-2.1.2
Parsing documentation for multi_json-1.14.1
Installing ri documentation for multi_json-1.14.1
Parsing documentation for httpclient-2.8.3
Installing ri documentation for httpclient-2.8.3
Parsing documentation for hocon-1.2.5
Installing ri documentation for hocon-1.2.5
Parsing documentation for puppet-resource_api-1.8.7
Installing ri documentation for puppet-resource_api-1.8.7
Parsing documentation for concurrent-ruby-1.1.5
Installing ri documentation for concurrent-ruby-1.1.5
Parsing documentation for win32-dir-0.4.9
Installing ri documentation for win32-dir-0.4.9
Parsing documentation for win32-process-0.7.5
Installing ri documentation for win32-process-0.7.5
Parsing documentation for win32-security-0.2.5
Installing ri documentation for win32-security-0.2.5
Parsing documentation for win32-service-0.8.8
Installing ri documentation for win32-service-0.8.8
Parsing documentation for minitar-0.6.1
Installing ri documentation for minitar-0.6.1
Parsing documentation for puppet-6.10.0-x64-mingw32
Installing ri documentation for puppet-6.10.0-x64-mingw32
Done installing documentation for facter, hiera, semantic_puppet, fast_gettext, locale, multi_json, httpclient, hocon, puppet-resource_api, concurrent-ruby, win32-dir, win32-process, win32-security, win32-service, minitar, puppet after 94 seconds
16 gems installed
```

### What is Expected?
Puppet!

### How Did You Get This To Happen? (Steps to Reproduce)
New laptop, fresh install of everything.  Start vscode, ka-boom.

### VSCode config is here:
```
{
    "files.eol": "\n",
    "files.insertFinalNewline": true,
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "window.zoomLevel": 0,
    "python.jediEnabled": false,
    "git.confirmSync": false,
    "git.enableSmartCommit": true,
    "ruby.codeCompletion": "rcodetools",
    "git.autofetch": true,
    "editor.formatOnSave": true,
    "git.autofetchPeriod": 14400,
    "team.showWelcomeMessage": false,
    "sync.gist": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "git.alwaysShowStagedChangesResourceGroup": true,
    "puppet.editorService.loglevel": "debug",
    "puppet.editorService.debugFilePath": "C:\\Users\\xxxxxxxxxxxxxxx\\OneDrive - Thomson Reuters Incorporated\\Desktop\\path.txt"
}
```
### Output Log
```
I, [2019-10-15T08:40:41.338667 #9472]  INFO -- : Language Server is v0.22.0
D, [2019-10-15T08:40:41.338667 #9472] DEBUG -- : Loading gems...
E, [2019-10-15T08:40:41.492364 #9472] ERROR -- : Error while loading a critical gem: cannot load such file -- puppet ["C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'", "C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'", "c:/Users/xxxxxxxxxxx/.vscode/extensions/jpogran.puppet-vscode-0.21.0/vendor/languageserver/lib/puppet_languageserver.rb:72:in `require_gems'", "c:/Users/xxxxxxxx/.vscode/extensions/jpogran.puppet-vscode-0.21.0/vendor/languageserver/lib/puppet_languageserver.rb:213:in `init_puppet'", "c:/Users/xxxxxxx/.vscode/extensions/jpogran.puppet-vscode-0.21.0/vendor/languageserver/puppet-languageserver:11:in `<main>'"]
I, [2019-10-15T08:40:41.492364 #9472]  INFO -- : Starting RPC Server...
I, [2019-10-15T08:40:41.492364 #9472]  INFO -- : Configured the Language Server to use the Disabled Message Router
D, [2019-10-15T08:40:41.492364 #9472] DEBUG -- : Using STDIO
I, [2019-10-15T08:40:41.492364 #9472]  INFO -- : Client has connected to the language server
D, [2019-10-15T08:40:41.492364 #9472] DEBUG -- : STDIOSRV: Starting STDIO server...
D, [2019-10-15T08:40:41.507984 #9472] DEBUG -- : --- INBOUND
```

**Comment by skywaymsn** [comment]
Edited to remove username

**Comment by jpogran** [comment]
Hi @skywaymsn, the Puppet Extension doesn't need you to install any gems and does not use your system ruby. It uses the ruby and gems that the PDK provides, so no further installations are necessary.

When you set `"puppet.editorService.loglevel": "debug"`, in addition to the log file you posted here there should also be output in the VSCode `Output Pane` under the `Puppet`. It should list something like this:

```

DEBUG: 2019-10-15T16:24:58.799Z Found a valid Puppet installation at C:\Program Files\Puppet Labs\DevelopmentKit\puppet
DEBUG: 2019-10-15T16:24:58.800Z Setting status bar to Initializing
DEBUG: 2019-10-15T16:24:58.800Z Configuring language client options
DEBUG: 2019-10-15T16:24:58.800Z Creating server options
DEBUG: 2019-10-15T16:24:58.800Z Starting language server client (host 127.0.0.1 port 8082)
DEBUG: 2019-10-15T16:24:58.800Z Creating language client
DEBUG: 2019-10-15T16:24:58.804Z Setting status bar to Initialization Complete
DEBUG: 2019-10-15T16:24:58.804Z Configuring Local::tcp connection handler
DEBUG: 2019-10-15T16:24:58.805Z [getRubyEnvFromPDK] Using environment variable RUBY_DIR=C:\Program Files\Puppet Labs\DevelopmentKit\private\ruby\2.5.7
DEBUG: 2019-10-15T16:24:58.805Z [getRubyEnvFromPDK] Using environment variable PATH=C:\Program Files\Puppet Labs\DevelopmentKit\bin;C:\Program Files\Puppet Labs\DevelopmentKit\private\ruby\2.5.7\bin;C:\WINDOWS\system32;C:\WINDOWS
DEBUG: 2019-10-15T16:24:58.805Z [getRubyEnvFromPDK] Using environment variable RUBYLIB=C:/Program Files/Puppet Labs/DevelopmentKit/lib;
DEBUG: 2019-10-15T16:24:58.805Z [getRubyEnvFromPDK] Using environment variable RUBYOPT=rubygems
DEBUG: 2019-10-15T16:24:58.805Z [getRubyEnvFromPDK] Using environment variable SSL_CERT_FILE=undefined
DEBUG: 2019-10-15T16:24:58.805Z [getRubyEnvFromPDK] Using environment variable SSL_CERT_DIR=undefined
DEBUG: 2019-10-15T16:24:58.805Z [getRubyEnvFromPDK] Using environment variable GEM_PATH=C:\Program Files\Puppet Labs\DevelopmentKit\private\ruby\2.5.7\lib\ruby\gems\2.5.0;C:\Program Files\Puppet Labs\DevelopmentKit\share\cache\ruby\2.5.0;C:\Program Files\Puppet Labs\DevelopmentKit\private\puppet\ruby\2.5.0
DEBUG: 2019-10-15T16:24:58.805Z [getRubyEnvFromPDK] Using environment variable GEM_HOME=C:\Program Files\Puppet Labs\DevelopmentKit\share\cache\ruby\2.5.0
DEBUG: 2019-10-15T16:24:58.805Z [getRubyEnvFromPDK] Editor Services will invoke with: C:\Program Files\Puppet Labs\DevelopmentKit\private\ruby\2.5.7\bin\ruby c:\Users\james\src\lingua\puppet-vscode\vendor\languageserver\puppet-languageserver --ip=127.0.0.1 --port=8082 --timeout=10 --debug=c:\Users\james\desktop\foo.txt
```

I'm looking for the parts where it shows where it found PDK, ruby, and the gem paths. I'm thinking something in your environment is preventing it from finding the correct paths

**Comment by skywaymsn** [comment]
Oddly, it had none of that.  Below is the full log, top-to-bottom.  However, I think I found the issue (thanks for the tip on Ruby) and it may be a PDK bug.  Details below the log.

```
I, [2019-10-15T10:23:53.204348 #5064]  INFO -- : Language Server is v0.22.0
D, [2019-10-15T10:23:53.205346 #5064] DEBUG -- : Loading gems...
W, [2019-10-15T10:23:53.283548 #5064]  WARN -- : Unable to use puppet version 5.5.16, as only the following versions are available []
E, [2019-10-15T10:23:53.355686 #5064] ERROR -- : Error while loading a critical gem: cannot load such file -- puppet ["C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'", "C:/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.4.9/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:54:in `require'", "c:/Users/xxxxxxxxxxxx/.vscode/extensions/jpogran.puppet-vscode-0.21.0/vendor/languageserver/lib/puppet_languageserver.rb:72:in `require_gems'", "c:/Users/xxxxxxxxxxxx/.vscode/extensions/jpogran.puppet-vscode-0.21.0/vendor/languageserver/lib/puppet_languageserver.rb:213:in `init_puppet'", "c:/Users/xxxxxxxxxxxx/.vscode/extensions/jpogran.puppet-vscode-0.21.0/vendor/languageserver/puppet-languageserver:11:in `<main>'"]
I, [2019-10-15T10:23:53.355686 #5064]  INFO -- : Starting RPC Server...
I, [2019-10-15T10:23:53.355686 #5064]  INFO -- : Configured the Language Server to use the Disabled Message Router
D, [2019-10-15T10:23:53.355686 #5064] DEBUG -- : Using STDIO
I, [2019-10-15T10:23:53.355686 #5064]  INFO -- : Client has connected to the language server
D, [2019-10-15T10:23:53.355686 #5064] DEBUG -- : STDIOSRV: Starting STDIO server...
D, [2019-10-15T10:23:53.355686 #5064] DEBUG -- : --- INBOUND
{"jsonrpc":"2.0","id":0,"method":"initialize","params":{"processId":11736,"rootPath":"c:\\Users\\xxxxxxxxxxxx\\Repositories","rootUri":"file:///c%3A/Users/xxxxxxxxxxxx/Repositories","capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","rename","delete"],"failureHandling":"textOnlyTransactional"},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"configuration":true,"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"],"parameterInformation":{"labelOffsetSupport":true}}},"definition":{"dynamicRegistration":true,"linkSupport":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true,"prepareSupport":true},"documentLink":{"dynamicRegistration":true},"typeDefinition":{"dynamicRegistration":true,"linkSupport":true},"implementation":{"dynamicRegistration":true,"linkSupport":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true},"declaration":{"dynamicRegistration":true,"linkSupport":true}}},"trace":"off","workspaceFolders":[{"uri":"file:///c%3A/Users/xxxxxxxxxxxx/Repositories","name":"Repositories"}]}}
---
D, [2019-10-15T10:23:53.355686 #5064] DEBUG -- : Received initialize method
D, [2019-10-15T10:23:53.355686 #5064] DEBUG -- : --- OUTBOUND
{"jsonrpc":"2.0","id":0,"result":{"capabilities":{}}}
---
D, [2019-10-15T10:23:53.872465 #5064] DEBUG -- : --- OUTBOUND
{"jsonrpc":"2.0","method":"window/showMessage","params":{"type":2,"message":"An error occured while the Language Server was starting. The server has been disabled."}}
---
D, [2019-10-15T10:23:53.872465 #5064] DEBUG -- : --- INBOUND
{"jsonrpc":"2.0","method":"initialized","params":{}}
---
I, [2019-10-15T10:23:53.872465 #5064]  INFO -- : Client has received initialization
D, [2019-10-15T10:23:54.370382 #5064] DEBUG -- : --- INBOUND
{"jsonrpc":"2.0","id":1,"method":"puppet/getVersion","params":null}
---
D, [2019-10-15T10:23:54.379374 #5064] DEBUG -- : --- OUTBOUND
{"jsonrpc":"2.0","id":1,"result":{"puppetVersion":"Unknown","facterVersion":"Unknown","languageServerVersion":null,"factsLoaded":true,"functionsLoaded":true,"typesLoaded":true,"classesLoaded":true}}
---

```

The error `Error while loading a critical gem: cannot load such file -- puppet` seemed to be the key.  I ran gitbash as admin and the following command:
`/c/Program Files/Puppet Labs/DevelopmentKit/private/ruby/2.4.9/bin/gem.bat install puppet`

This produced the following output:

```
Successfully installed hiera-3.6.0
Successfully installed semantic_puppet-1.0.2
Successfully installed multi_json-1.14.1
Successfully installed hocon-1.2.5
Successfully installed puppet-resource_api-1.8.7
Successfully installed win32-dir-0.4.9
Successfully installed win32-process-0.7.5
Successfully installed win32-security-0.2.5
Successfully installed win32-service-0.8.8
Successfully installed puppet-6.10.1-x64-mingw32
Parsing documentation for hiera-3.6.0
Installing ri documentation for hiera-3.6.0
Parsing documentation for semantic_puppet-1.0.2
Installing ri documentation for semantic_puppet-1.0.2
Parsing documentation for multi_json-1.14.1
Installing ri documentation for multi_json-1.14.1
Parsing documentation for hocon-1.2.5
Installing ri documentation for hocon-1.2.5
Parsing documentation for puppet-resource_api-1.8.7
Installing ri documentation for puppet-resource_api-1.8.7
Parsing documentation for win32-dir-0.4.9
Installing ri documentation for win32-dir-0.4.9
Parsing documentation for win32-process-0.7.5
Installing ri documentation for win32-process-0.7.5
Parsing documentation for win32-security-0.2.5
Installing ri documentation for win32-security-0.2.5
Parsing documentation for win32-service-0.8.8
Installing ri documentation for win32-service-0.8.8
Parsing documentation for puppet-6.10.1-x64-mingw32
Installing ri documentation for puppet-6.10.1-x64-mingw32
Done installing documentation for hiera, semantic_puppet, multi_json, hocon, puppet-resource_api, win32-dir, win32-process, win32-security, win32-service, puppet after 84 seconds
10 gems installed
```

Now I'm off and running.

The only thing I can think of is that either the latest PDK isn't bundling the puppet gem (and it should) or some other thing is supposed to provide that gem and isn't or can't, possibly due to permissions.

**Comment by skywaymsn** [comment]
Correction, I'm off and running to the effect that I can *only* use puppet 6.10.1 which matches the version of the installed gem.

**Comment by jpogran** [comment]
The pane I'm refering to is inside the VSCode window, not the log file. The log file comes from the pupept language server process, the `Output Pane` is in the VSCode window like the screenshot below.

![image](https://user-images.githubusercontent.com/272569/66852072-26422c00-ef4a-11e9-9b08-a14f25588a40.png)

**Comment by jpogran** [comment]
You're getting a red-herring by installing things manually. The extension finds where you installed PDK, then finds the ruby versions that PDK install has, then adds the gems for the version of ruby selected. There are no external dependencies used. This allows us to give you a menu of Puppet versions to choose from.

If you would like to debug realtime, I'm in the puppetcommunity.slack.com slack. Either #puppet-dev or #puppet rooms are fine

**Comment by skywaymsn** [comment]
I can add individual puppet versions by forcing in versions of the gem with: `gem.bat install puppet --version "5.5.16"`  etc.

The log you are after is below.  With a manual install of puppet gem 6.10.1 and 5.5.16, it behaves normally-ish (limited to manually installed versions).

```
DEBUG: 2019-10-15T16:57:43.895Z Registered extension.pdkNewModule command
DEBUG: 2019-10-15T16:57:43.895Z Registered extension.pdkNewClass command
DEBUG: 2019-10-15T16:57:43.895Z Registered extension.pdkNewTask command
DEBUG: 2019-10-15T16:57:43.895Z Registered extension.pdkValidate command
DEBUG: 2019-10-15T16:57:43.895Z Registered extension.pdkTestUnit command
DEBUG: 2019-10-15T16:57:43.895Z Found a valid Puppet installation at C:\Program Files\Puppet Labs\DevelopmentKit\puppet
DEBUG: 2019-10-15T16:57:43.895Z Setting status bar to Initializing
DEBUG: 2019-10-15T16:57:43.896Z Configuring language client options
DEBUG: 2019-10-15T16:57:43.896Z Creating server options
DEBUG: 2019-10-15T16:57:43.897Z [getRubyEnvFromPDK] Using environment variable DEVKIT_BASEDIR=C:\Program Files\Puppet Labs\DevelopmentKit
DEBUG: 2019-10-15T16:57:43.897Z [getRubyEnvFromPDK] Using environment variable GEM_HOME=C:\Program Files\Puppet Labs\DevelopmentKit\share\cache\ruby\2.4.0
DEBUG: 2019-10-15T16:57:43.897Z [getRubyEnvFromPDK] Using environment variable GEM_PATH=C:\Program Files\Puppet Labs\DevelopmentKit\private\ruby\2.4.9\lib\ruby\gems\2.4.0;C:\Program Files\Puppet Labs\DevelopmentKit\share\cache\ruby\2.4.0;C:\Program Files\Puppet Labs\DevelopmentKit\private\puppet\ruby\2.4.0
DEBUG: 2019-10-15T16:57:43.897Z [getRubyEnvFromPDK] Using environment variable RUBY_DIR=C:\Program Files\Puppet Labs\DevelopmentKit\private\ruby\2.4.9
DEBUG: 2019-10-15T16:57:43.897Z [getRubyEnvFromPDK] Using environment variable RUBYLIB=C:/Program Files/Puppet Labs/DevelopmentKit/lib;
DEBUG: 2019-10-15T16:57:43.897Z [getRubyEnvFromPDK] Using environment variable PATH=C:\Program Files\Puppet Labs\DevelopmentKit\bin;C:\Program Files\Puppet Labs\DevelopmentKit\private\ruby\2.4.9\bin;C:\Program Files (x86)\Amazon Corretto\jdk1.8.0_222\bin;C:\Program Files\Amazon Corretto\jdk1.8.0_222\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Plantronics\Spokes3G\;C:\Program Files\Git\cmd;C:\Program Files\Puppet Labs\Puppet\bin;C:\Ruby26-x64\bin;C:\Users\xxxxxxxxxxx\AppData\Local\Microsoft\WindowsApps;;C:\Users\xxxxxxxxxxx\AppData\Local\Programs\Microsoft VS Code\bin
DEBUG: 2019-10-15T16:57:43.897Z [getRubyEnvFromPDK] Using environment variable RUBYOPT=rubygems
DEBUG: 2019-10-15T16:57:43.897Z [getRubyEnvFromPDK] Editor Services will invoke with: C:\Program Files\Puppet Labs\DevelopmentKit\private\ruby\2.4.9\bin\ruby c:\Users\xxxxxxxxxxx\.vscode\extensions\jpogran.puppet-vscode-0.21.0\vendor\languageserver\puppet-languageserver --stdio --timeout=10 --local-workspace=c:\Users\xxxxxxxxxxx\Repositories --puppet-version=5.5.16 --debug=C:\Users\xxxxxxxxxxx\OneDrive - Thomson Reuters Incorporated\Desktop\path.txt
DEBUG: 2019-10-15T16:57:43.897Z Creating language client
DEBUG: 2019-10-15T16:57:43.900Z Setting status bar to Initialization Complete
DEBUG: 2019-10-15T16:57:43.900Z Configuring Local::stdio connection handler
DEBUG: 2019-10-15T16:57:43.900Z Setting status bar to Starting languageserver
DEBUG: 2019-10-15T16:57:43.900Z Registered Format Document provider
DEBUG: 2019-10-15T16:57:43.900Z Registered extension.puppetShowNodeGraphToSide command
DEBUG: 2019-10-15T16:57:43.900Z Registered onDidSaveTextDocument for node graph event handler
DEBUG: 2019-10-15T16:57:43.901Z Registered DebugAdapterDescriptorFactory for Puppet
DEBUG: 2019-10-15T16:57:43.901Z Registered DebugConfigurationProvider for Puppet
DEBUG: 2019-10-15T16:57:44.577Z pdk shell started, pid: 14176
DEBUG: 2019-10-15T16:57:50.937Z Setting status bar to Loading Puppet
DEBUG: 2019-10-15T16:57:52.169Z Setting status bar to 5.5.16
DEBUG: 2019-10-15T16:57:54.331Z Setting status bar to 5.5.16
DEBUG: 2019-10-15T16:57:54.356Z Setting status bar to 5.5.16
DEBUG: 2019-10-15T16:57:54.965Z Setting status bar to 5.5.16
DEBUG: 2019-10-15T16:57:56.927Z Setting status bar to 5.5.16
DEBUG: 2019-10-15T16:57:57.837Z Setting status bar to 5.5.16
DEBUG: 2019-10-15T16:57:58.488Z Setting status bar to 5.5.16
DEBUG: 2019-10-15T16:57:59.142Z Setting status bar to 5.5.16
DEBUG: 2019-10-15T16:57:59.971Z Setting status bar to 5.5.16
DEBUG: 2019-10-15T16:58:00.971Z Setting status bar to 5.5.16
DEBUG: 2019-10-15T16:58:01.962Z Setting status bar to 5.5.16
DEBUG: 2019-10-15T16:58:02.973Z Setting status bar to 5.5.16
DEBUG: 2019-10-15T16:58:03.973Z Setting status bar to 5.5.16
DEBUG: 2019-10-15T16:58:04.969Z Setting status bar to 5.5.16

```

**Comment by skywaymsn** [comment]
I tried to join PuppetCommunity on Slack by applying here: https://slack.puppet.com/ but my invite has not arrived.

**Comment by skywaymsn** [comment]
Correction, my work email did not see the invite, but I'm in under a personal account.

**Comment by jpogran** [comment]
Great! Ping me directly (james pogran) or in any of the channels I mentioned.

**Comment by jpogran** [comment]
This turned out to be a PDK install that was missing most of the install files, most likely due to an overeager AV scanner intercepting file write calls. Once PDK was uninstalled and reinstalled, everything worked fine. Closing this issue
